version: '2'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    hostname: web
    ports:
        - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis
    hostname: redis
