version: '2'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    hostname: web
    ports:
        - "5000:5000"
    depends_on:
      - redis
    environment:
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - ACCESS_TOKEN_KEY
      - ACCESS_TOKEN_SECRET
  redis:
    image: redis
    hostname: redis
