import os

DEBUG = True

CONSUMER_KEY = os.environ["CONSUMER_KEY"]
CONSUMER_SECRET = os.environ["CONSUMER_SECRET"]
ACCESS_TOKEN_KEY = os.environ["ACCESS_TOKEN_KEY"]
ACCESS_TOKEN_SECRET = os.environ["ACCESS_TOKEN_SECRET"]

USERNAME = '@realdonaldtrump'
NUMBER_OF_TWEETS = 100

REDIS_HOST = 'redis'
REDIS_PORT = 6379

CACHE_TTL = 60 * 60
